### ISSUE TITLE
Provide a "default" sketching form as download with DSL logo

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#402]
Provide a standardised template form under "download" for sketching of deepsky objects.
Basis can be the older VVS form, but I would like to rework this a little bit to suit modern needs of visual observers. Of course with the DeepskyLog logo on top!

**Comment by WimDeMeester** [comment]
Good plan! Can you start working on a template?

**Comment by rolfvandervleuten** [comment]
A proposal for a default template. I use it myself and find it convenient to use. It folds in half so it fits on top of your PSA ;)
![observatie](https://cloud.githubusercontent.com/assets/1202239/9520776/3e6d1bc2-4cca-11e5-865b-b644af773635.png)

**Comment by TomCorstjens** [comment]
Good first concept! 

What is the diameter of the circle? With modern widefield eyepieces, the diameter should be enlarged to allow plotting the bigger fielld of view. Most observers prefer nowadays a diameter of 15 - 16 cm. That is difficult to match with 2 observations on 1 A4 page.

Some other ideas / suggestions: 
- remove the banner on the left side. Little added value and take a lot of space.
- add name of observer
- Add transparancy / SQM-L value / NELM (naked eyen limiting magnitude) value

Also think it is easier to use when making the form in regular Portrait, not Landscape format.
You could put the drawing circle then on the left side, and the notes field on the right side.

Final comment: no frames around the entry fields. Makes it heavy. 
At max. a horizontal line between info and notes.

**Comment by rolfvandervleuten** [comment]
Maybe we can do 2 versions, a large one and a compact one.
I just added the banner to the left to fill the space, and we wanted to put the logo somewhere.

so how about this for a large version?

I'm not so sure about the logo in the bottom, maybe there is another image available for this?

![observatie groot](https://cloud.githubusercontent.com/assets/1202239/9531642/4d638afc-4d07-11e5-96fe-a9dc03560e9b.png)

**Comment by WimDeMeester** [comment]
Looks fine to me. Maybe we can add the two forms? Anyone interested in designing a page where the forms can be downloaded (can be in Word for example). Once we have the forms and the page, this is easy to add to DeepskyLog.

**Comment by SkyNomad** [comment]
Perfect! Some observing-support material, like observing sheets would certainly have a good place on DeepskyLog!

The problem is that an observing form is always a little personal. I also prefer to draw in a larger circle than Tom. My default form puts the circle in a position on the paper so I can sketch both in portrait and landscape orientation. Other people will have different preferences...

I suggest that all forms posted at least have an identical layout for the square area surrounding the circle (proportion of line width to diameter / orientation marks / white space), because this will be scanned:

![circle](https://cloud.githubusercontent.com/assets/12213599/9698557/6672eae0-53bc-11e5-8d09-f4e97cacd007.png)



Many sketches from different observers on DeepskyLog include data around the drawing circle, which is is subsequently included on the scan of the sketch. IF we want this to contain datafields, those could be:

* the object name;
* drawing serial number;
* true field of view;
* telecope aperture.

In addition, wouldn't it be good to define a 'preferred' scanning proces (scan size, colordepth, ..)? I'm sure other people have more experience & suggestions on this.



Just for your information, I currently use two forms: one for logging, one for sketching (without the information around):

![obverving form2](https://cloud.githubusercontent.com/assets/12213599/9698458/9dba8bca-53b7-11e5-9593-13a3103fab7b.png)

![obverving form1](https://cloud.githubusercontent.com/assets/12213599/9698461/a42d24d6-53b7-11e5-853b-ad0d1a695531.png)

**Comment by rolfvandervleuten** [comment]
The two designs with some adjustments according to previous comments
![observatie groot 1](https://cloud.githubusercontent.com/assets/1202239/9698629/e0b7da74-53bf-11e5-8fcf-24d922389f5c.png)
![observatie](https://cloud.githubusercontent.com/assets/1202239/9698630/e2f8ce24-53bf-11e5-9949-f245895f4585.png)

**Comment by WimDeMeester** [comment]
I don't think we can create an observation sheet that is acceptable for all observers. I don't even think that we should try to make such one. For me, the two sheets made by @rolfvandervleuten are fine to add. Maybe we should also make a sheet for logging, based on the one by @SkyNomad , but with the DeepskyLog logo. Providing 3 sheets in DeepskyLog looks very nice to me. What do you think @SkyNomad , @rolfvandervleuten and @TomCorstjens ?

**Comment by rolfvandervleuten** [comment]
Ok, I'll convert @SkyNomad 's log sheet so it matches the other two, and add a logo

**Comment by SkyNomad** [comment]
I'm fine with any of the layouts above : they are all designed very well & I would be happy to use any of them - just made some suggestions! @rolfvandervleuten : do you want my .doc files?

**Comment by rolfvandervleuten** [comment]
@SkyNomad thank you, but I'm gonna put it in an other format anyway, so no need for the doc files

**Comment by rolfvandervleuten** [comment]
![observation log](https://cloud.githubusercontent.com/assets/1202239/9831298/0c7d4c16-5951-11e5-9264-41f5e042c118.png)

**Comment by WimDeMeester** [comment]
All forms look fine. Do you make a page where you can download the pdf files? I can also do it, but then I need the pdf files ;-) I propose to add a menu item in 'Downloads' and a page like the 'Atlases' page.

**Comment by SkyNomad** [comment]
@rolfvandervleuten 
Nice work!
I recommend to list only 5 objects on the form "observation log", to get a bit more room to write comments. Something that annoyed me last weekend on my own form...
