### ISSUE TITLE
Default language in "search observation query" is DUTCH

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#562]
Workshop session Urania: 
When a new user makes first login 
and does not fill in a search value
and presses "search observation button
--> the query menu "searches an observation" appears. OK. 

BUT:  the default language value for the search functionality is DUTCH. 
=> This must be either ALL languages, either at least including ENGLISH.

**Comment by WimDeMeester** [comment]
This is not exactly what is happening. First of all, the user has the possibility to change the languages he wants to see when doing the registration. The Urania test users could not do this because I was doing the registrations. 
When doing the registration, the default values for the languages the observers want to see depends on the site you are using for the registration. For:

+ www.deepskylog.be: en, nl
+ www.deepskylog.de: de
+ www.deepskylog.de: fr
+ www.deepskylog.nl: en, nl
+ www.deepskylog.org: en
+ www.deepskylog.se: se
+ test-server: en, nl

I think we can close this issue.

**Comment by TomCorstjens** [comment]
Agreed to close, was no aware that languages are selected when registering.
