### ISSUE TITLE
Sorting field above colomns: used as "search" field

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#567]
WORKSHOP URANIA: 

A new user that just succesfully found his first list of observations of M46 (:-)) and wanted to search another object. 
--> he used the sort field on top of the table als entry field to search another object (e.g. M101). 
It was not clear where this field was used for (for sorting, not searching). 

SUGGESTED to pre-fill the word "sort" to make clear this is for sorting, not searching

![sort_entry](https://cloud.githubusercontent.com/assets/12647470/12360698/cb2e397a-bbb9-11e5-86d3-a0cc5947a4d6.PNG)

**Comment by rolfvandervleuten** [comment]
will be different in datatables. there is only 1 search field to search through the results.
It is now called 'search' maybe change this to 'filter' ?

**Comment by WimDeMeester** [comment]
Will change this to filter in the laravel version of DeepskyLog.

**Comment by WimDeMeester** [comment]
In the laravel version of DeepskyLog, there will be one search field. See the screenshot.

![image](https://user-images.githubusercontent.com/7261529/74540896-e2cfec80-4f40-11ea-8994-06eb81c45af5.png)

It is impossible to change the name, certainly if we want to use internationalisation. Closing this ticket because the 'Search' field is a de factor internet standard.
