### ISSUE TITLE
New location: La Silla is "default" google maps location

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#575]
URANIA WORKSHOP: 

When creating a new observing location, the Google Maps plugin suggests La Silla in Chili as default location. 

1. require extensive scrolling to get to Europe ... (instead entering the location in the top field)
-> not user friendly. 
===> Better to set a European location (e.g. Leuven) 

2. Not clear that your own location also needs a user-defined naming (in the field below google map)
===> requires better explanation e.g. "DEFINE YOUR OWN NAME FOR THIS LOCATION:" together with the button "add location"

![lasilla](https://cloud.githubusercontent.com/assets/12647470/12362807/8f5b51f6-bbc5-11e5-8659-0b0a67bf4301.PNG)

**Comment by WimDeMeester** [comment]
1. Normally, the browser gives back the location of the computer where DeepskyLog is running. this is very accurate, if I do this from home, I can see that my house is indeed selected and put in the map as standard location.
If the browser is denied to get the location, the standard location is indeed set to La Silla.  Because DeepskyLog is NOT for European users only, I used a well known international observatory. It is easy to find a city nearby the location you want to enter by just entering it in the search field. 

2. This should indeed be much clearer.

**Comment by TomCorstjens** [comment]
Agreed for (1) - issue appeared because location was denied to browser. 
Rationale for La Silla is understood - why not selecting the ESO site at la Palma? This will receive more "understanding" as feasible 'ultimate observing location'

**Comment by WimDeMeester** [comment]
The site at La Palma is not from the ESO. Most of the telescope at La Palma are telescopes set up by different countries. The countries are all part of the IAC (Instituto Astrofysico de Canarias), but that is not to be compared with the ESO. Anyway, I'm 100% certain that the site at La Palma is not as well known as the site in Chile by the majority of the observers. 
Anyway, this is a small change to make. So if we really want to have La Palma instead of La Silla, that can be done.

**Comment by WimDeMeester** [comment]
Added some text to make the page clearer.

**Comment by TomCorstjens** [comment]
Text clarifies already a lot. Good improvement.
About choice of site: let it be for the moment :-)
