### ISSUE TITLE
NGC 5602

### ISSUE THREAD

**Issue by torbjornholmqvist** [DeepskyLog/DeepskyLog#630]
Hello,
Isn´t NGC 5602 a Herschel 400-II object? I observed it this morning and when I added it to the data base it does not seem to be counted as a Herschel 400-II object.
Best regards,
Torbjörn Holmqvist

**Comment by TomCorstjens** [comment]
There is some discussion about 2 different objects that either belong to the Herschel 400-II list. 
- One souce mentions NGC 5602 as part of H400-II
- Another source mentions NGC 5756 as part of H400-II

Deepskylog team has chosen to select NGC 5756 as the official member, because NGC 5602 is more than a magnitude fainter. In the philosophy of the H400-II list, brightest members are included.

There is a "public list" Herschel 400-II" that includes NGC 5602; in case you also want to score 100% on that list -> also observe it :-))
