### ISSUE TITLE
One cannot update a location with a subset of possible data to add

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#691]
For example, if I know the SQM value but not the NELM, I cannot add the SQM value to a location. The system generates an error when I only enter the SQM value, but not the NELM.

This is on an iPad pro with iOS 11.2, but the issue appears to be generic.

**Comment by WimDeMeester** [comment]
I can not reproduce this. So, you have a SQM and try to update it? Or don't you have an SQM yet and try to add a new one?

**Comment by svdwal** [comment]
I do not hav an SQM, and I try to update it

**Comment by WimDeMeester** [comment]
Can you try this again? I have made some changes, but I'm not sure if this will fix your problem. If there is still an error, can you add the error to this issue?

**Comment by svdwal** [comment]
There's still an error. You get a popup when the list of locations is shown again.

![1f3f6847-2945-4641-931c-a679e67c0c5a](https://user-images.githubusercontent.com/18214836/36933738-9c3dce98-1ede-11e8-8de8-b80b23aad750.png)

**Comment by WimDeMeester** [comment]
The code returns this error if the name or the country is not given: 
`($objUtil->checkPostKey('locationname') && $objUtil->checkPostKey('country' ))`

The country should be automatically retrieved from the coordinates, so that should not be a problem. I guess the name is also given... Can you tell me which location you want to change? I can then use that location in my test environment to reproduce (and fix) the problem.

**Comment by svdwal** [comment]
The location is 'Leiden - Oude Sterrewacht'

**Comment by WimDeMeester** [comment]
This problems in fixed in the laravel version of DeepskyLog. Closing it.
